### ISSUE TITLE
ModuleNotFoundError: No module named 'detectron2.config'，from detectron2.config import get_cfg

### ISSUE THREAD

**Issue by zhaoleo1111** [RomeoSajina/PoseTracking#1]
where is the ‘get_cfg’ file

**Comment by RomeoSajina** [comment]
Detectron2 needs to be installed:

`
$ cd detectron2

$ python -m pip install -e detectron2
# Or if you are on macOS
$ CC=clang CXX=clang++ python -m pip install -e detectron2
`

I think there is no need to have detectron2 within the project as it can be easily installed with `pip install git+https://github.com/facebookresearch/detectron2.git`. I might refactor this in the future.

**Comment by RomeoSajina** [comment]
detectron2 now should be installed using pip. Closing the issue (see [fb6b1d7](https://github.com/RomeoSajina/PoseTracking/commit/fb6b1d7c2edd5845f29494be36623e2285dc3fb0))
